#pragma once
#define _STR(x) _STR_(x)
#define _STR_(x) #x

#define VERSION_MAJOR 0
#define VERSION_MINOR 2
#define VERSION_REVISION 0
#define VERSION_PATCH 1

#define FILE_DESCRIPTION "VI - 可视化INI"
#define FILE_VERSION_STR _STR(VERSION_MAJOR) "." _STR(VERSION_MINOR) "." _STR(VERSION_REVISION) "." _STR(VERSION_PATCH)
#define FILE_VERSION VERSION_MAJOR, VERSION_MINOR, VERSION_REVISION, VERSION_PATCH
#define PRODUCT_VERSION "Version " FILE_VERSION_STR

#define IDI_ICON1                       101
